# SkosConcept 
SELECT DISTINCT ?SkosConcept_url ?prefLabel ?definition ?altLabel ?parentCode_url ?relatedCode_url ?naam ?isSpecialisatieVan_url WHERE {
  ?SkosConcept_url a <http://www.w3.org/2004/02/skos/core#Concept> .
  OPTIONAL { ?SkosConcept_url <http://www.w3.org/2004/02/skos/core#prefLabel> ?prefLabel . }
  OPTIONAL { ?SkosConcept_url <http://www.w3.org/2004/02/skos/core#definition> ?definition . }
  OPTIONAL { ?SkosConcept_url <http://www.w3.org/2004/02/skos/core#altLabel> ?altLabel . }
  OPTIONAL { ?SkosConcept_url <http://www.w3.org/2004/02/skos/core#broader> ?parentCode_url . }
  OPTIONAL { ?SkosConcept_url <http://www.w3.org/2004/02/skos/core#related> ?relatedCode_url . }
  OPTIONAL { ?SkosConcept_url <http://purl.org/dc/terms/title> ?naam . }
  OPTIONAL { ?SkosConcept_url <http://www.w3.org/2004/02/skos/core#broader> ?isSpecialisatieVan_url . }
}
