# Stopzetting 
SELECT DISTINCT ?Stopzetting_url ?redenStopzetting_url WHERE {
  ?Stopzetting_url a <https://data.vlaanderen.be/ns/organisatie#Stopzetting> .
  OPTIONAL { ?Stopzetting_url <https://data.vlaanderen.be/ns/organisatie#redenStopzetting> ?redenStopzetting_url . }
}
